-- JULIAN CRISTANCHO
-- MARIANA GORDILLO
-- BRIAN VARGAS
-- GRUPO 1

-- CREACIÓN DE LA TABLA DE AUDITORIA
CREATE TABLE
    IF NOT EXISTS AU_PROV (
        id_au INT GENERATED ALWAYS AS IDENTITY (
            START
            WITH
                1 INCREMENT BY 1
        ) PRIMARY KEY,
        fecha_sis DATE,
        COD_PRV CHAR(5),
        COD_DIS CHAR(5)
    );

-- CREACIÓN DEL TRIGGER
CREATE TRIGGER TRIGGER_INSERT_PROV_AU_PROV
AFTER INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
    INSERT INTO AU_PROV (fecha_sis, COD_PRV, COD_DIS)
    VALUES (SYSDATE, :NEW.COD_PRV, :NEW.COD_DIS);
END;

-- INSERT PARA PROBAR EL TRIGGER
INSERT INTO
    PROVEEDOR
VALUES
    (
        'PR30',
        'PIRAMIDE JULIANCHO',
        'KONRAD LORENZ',
        '3124561523',
        'D13',
        'JULIAN CRISTANCHO'
    );