-- =========================================
-- TABLA Y PROCEDIMIENTO DE AUDITORÍA
-- Archivo: 4.1 - Tabla Auditoria.sql
-- Descripción: Definición de la tabla de auditoría y ejemplo de procedimiento
-- =========================================

-- =========================================
-- CREACIÓN DE LA TABLA AUDITORIA
-- =========================================
CREATE TABLE AUDITORIA (
    ID_AUDITORIA     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USUARIO          VARCHAR2(50),
    FECHA_HORA       TIMESTAMP DEFAULT SYSTIMESTAMP,
    TABLA_AFECTADA   VARCHAR2(50),
    TIPO_OPERACION   VARCHAR2(10), -- 'INSERT', 'UPDATE' o 'DELETE'
    DESCRIPCION      VARCHAR2(4000)
);

-- =========================================
-- PROCEDIMIENTO PARA REGISTRAR AUDITORÍA
-- =========================================
CREATE OR REPLACE PROCEDURE REGISTRAR_AUDITORIA (
    p_tabla         VARCHAR2,
    p_operacion     VARCHAR2,
    p_descripcion   VARCHAR2
)
IS
BEGIN
    INSERT INTO AUDITORIA (USUARIO, TABLA_AFECTADA, TIPO_OPERACION, DESCRIPCION)
    VALUES (USER, p_tabla, p_operacion, p_descripcion);
    COMMIT;
END;
/